//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Database
{
    using Diggity.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DayOfWeek = Diggity.Entities.DayOfWeek;
    
    
    public partial class ModelContainer : DbContext
    {
    
    	public ModelContainer(string connectionString): base(connectionString)
        {            
        }
    
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<ExerciseType> ExerciseTypes { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<Workout> Workouts { get; set; }
        public virtual DbSet<WorkoutSet> WorkoutSets { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<PersonalRecord> PersonalRecords { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<WorkoutTemplate> WorkoutTemplates { get; set; }
        public virtual DbSet<TemplateDays> TemplateDays { get; set; }
        public virtual DbSet<DayOfWeek> DayOfWeeks { get; set; }
        public virtual DbSet<WodUnitType> WodUnitTypes { get; set; }
        public virtual DbSet<WodUnitOfMeasure> WodUnitOfMeasures { get; set; }
        public virtual DbSet<Wod> Wods { get; set; }
        public virtual DbSet<WodRound> WodRounds { get; set; }
        public virtual DbSet<WodExercise> WodExercises { get; set; }
        public virtual DbSet<WendlerGroup> WendlerGroups { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
