//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDays : DiggityEntity
    {
        public TemplateDays()
        {
            this.WorkoutSets = new HashSet<WorkoutSet>();
        }
    
        public int Id { get; set; }
        public bool IsRepeat { get; set; }
        public int WorkoutTemplateId { get; set; }
        public int DayOfWeekId { get; set; }
    
        public virtual ICollection<WorkoutSet> WorkoutSets { get; set; }
        public virtual WorkoutTemplate WorkoutTemplate { get; set; }
        public virtual DayOfWeek DayOfWeek { get; set; }
    }
}
