//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wod : DiggityEntity
    {
        public Wod()
        {
            this.WodRounds = new HashSet<WodRound>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public int WodUnitOfMeasureId { get; set; }
    
        public virtual ICollection<WodRound> WodRounds { get; set; }
        public virtual WodUnitOfMeasure WodUnitOfMeasure { get; set; }
    }
}
