//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WodExercise : DiggityEntity
    {
        public int Id { get; set; }
        public int WodRoundId { get; set; }
        public int ExerciseId { get; set; }
        public double Value { get; set; }
        public int UnitOfMeasureId { get; set; }
        public Nullable<short> Reps { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual WodRound WodRound { get; set; }
        public virtual Exercise Exercise { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
