//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WodUnitType : DiggityEntity
    {
        public WodUnitType()
        {
            this.WodUnitOfMeasures = new HashSet<WodUnitOfMeasure>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
    
        public virtual ICollection<WodUnitOfMeasure> WodUnitOfMeasures { get; set; }
    }
}
