//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WodUnitOfMeasure : DiggityEntity
    {
        public WodUnitOfMeasure()
        {
            this.Wods = new HashSet<Wod>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int WodUnitTypeId { get; set; }
    
        public virtual WodUnitType WodUnitType { get; set; }
        public virtual ICollection<Wod> Wods { get; set; }
    }
}
