//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutSet : DiggityEntity, IEntity
    {
        public int Id { get; set; }
        public string SortOrder { get; set; }
        public string PlannedReps { get; set; }
        public string ActualReps { get; set; }
        public string PlannedWeight { get; set; }
        public string ActualWeight { get; set; }
        public int UnitOfMeasureId { get; set; }
        public int ExerciseId { get; set; }
        public int WorkoutId { get; set; }
    
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual Exercise Exercise { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
