//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutSet : DiggityEntity
    {
        public int Id { get; set; }
        public short SortOrder { get; set; }
        public short Repetitions { get; set; }
        public double Weight { get; set; }
        public string Note { get; set; }
        public int ExerciseId { get; set; }
        public int UnitOfMeasureId { get; set; }
        public Nullable<int> WorkoutId { get; set; }
        public Nullable<int> TemplateDaysId { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual Workout Workout { get; set; }
        public virtual TemplateDays TemplateDay { get; set; }
    }
}
