//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diggity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public int ExerciseTypeId { get; set; }
        public int UnitOfMeasureId { get; set; }
        public int UserId { get; set; }
    
        public virtual ExerciseType ExerciseType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual User User { get; set; }
    }
}
